(() => {
  'use strict';
  const W=1000,H=600, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const $=id=>document.getElementById(id);

  class InputManager{
    constructor(){this.keys={};const map={ArrowUp:'forward',KeyW:'forward',ArrowDown:'back',KeyS:'back',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right'};
      addEventListener('keydown',e=>{if(map[e.code]){this.keys[map[e.code]]=true;e.preventDefault()}if((e.code==='KeyP'||e.code==='Escape')&&!e.repeat)game.togglePause()},{passive:false});
      addEventListener('keyup',e=>{if(map[e.code]){this.keys[map[e.code]]=false;e.preventDefault()}},{passive:false});
      document.querySelectorAll('[data-control]').forEach(b=>{const key=b.dataset.control,set=v=>{this.keys[key]=v;b.classList.toggle('active',v)};b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true)});['pointerup','pointercancel','lostpointercapture'].forEach(n=>b.addEventListener(n,()=>set(false)))})
    }
    clear(){this.keys={};document.querySelectorAll('.active').forEach(x=>x.classList.remove('active'))}
  }
  class AudioManager{
    constructor(){this.enabled=localStorage.getItem('ef-sound')!=='false';this.ctx=null;this.musicTimer=null;this.musicStep=0;this.musicGain=null}
    init(){if(!this.ctx)try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.musicGain=this.ctx.createGain();this.musicGain.gain.value=.035;this.musicGain.connect(this.ctx.destination)}catch(e){this.enabled=false}if(this.ctx?.state==='suspended')this.ctx.resume()}
    tone(freq,dur,type='sine',vol=.08,delay=0){if(!this.enabled)return;this.init();if(!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+dur)}
    crash(){this.tone(90,.2,'sawtooth',.13)} park(){this.tone(520,.12);this.tone(780,.18,'sine',.1,.12)} complete(){[440,554,659,880].forEach((f,i)=>this.tone(f,.25,'triangle',.1,i*.12))}
    startMusic(){if(!this.enabled||this.musicTimer)return;this.init();if(!this.ctx||!this.musicGain)return;this.musicGain.gain.setTargetAtTime(.035,this.ctx.currentTime,.08);const melody=[261.63,329.63,392,329.63,293.66,349.23,440,349.23,246.94,293.66,392,293.66,220,261.63,329.63,392];const bass=[130.81,130.81,146.83,146.83,123.47,123.47,110,110];const play=()=>{if(!this.enabled||!this.musicTimer)return;const i=this.musicStep++;this.musicNote(melody[i%melody.length],.22,'triangle',.65);if(i%2===0)this.musicNote(bass[Math.floor(i/2)%bass.length],.42,'sine',.75);this.musicTimer=setTimeout(play,300)};this.musicTimer=setTimeout(play,20)}
    musicNote(freq,dur,type,volume){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(this.musicGain);o.start(t);o.stop(t+dur+.03)}
    stopMusic(){if(this.musicTimer){clearTimeout(this.musicTimer);this.musicTimer=null}if(this.ctx&&this.musicGain)this.musicGain.gain.setTargetAtTime(.0001,this.ctx.currentTime,.04)}
    toggle(){this.enabled=!this.enabled;localStorage.setItem('ef-sound',this.enabled);if(!this.enabled)this.stopMusic();return this.enabled}
  }
  class Car{
    constructor(x,y,a,color='#34a6ff'){Object.assign(this,{x,y,a,color,speed:0,w:34,h:62})}
    update(dt,input){let accel=0;if(input.keys.back)accel=this.speed>0?-320:-135;else if(input.keys.forward)accel=this.speed<0?260:150;if(accel){const before=this.speed;this.speed+=accel*dt;if(input.keys.back&&before>0&&this.speed<0)this.speed=0;if(input.keys.forward&&before<0&&this.speed>0)this.speed=0}else this.speed*=Math.pow(.18,dt);this.speed=clamp(this.speed,-82,175);if(Math.abs(this.speed)<.8)this.speed=0;const steer=(input.keys.right?1:0)-(input.keys.left?1:0);if(steer&&Math.abs(this.speed)>2)this.a+=steer*1.85*dt*clamp(Math.abs(this.speed)/70,.25,1)*(this.speed>0?1:-1);this.x+=Math.sin(this.a)*this.speed*dt;this.y-=Math.cos(this.a)*this.speed*dt}
    corners(x=this.x,y=this.y,a=this.a,w=this.w,h=this.h){const c=Math.cos(a),s=Math.sin(a),hw=w/2,hh=h/2;return [[-hw,-hh],[hw,-hh],[hw,hh],[-hw,hh]].map(([px,py])=>({x:x+px*c-py*s,y:y+px*s+py*c}))}
    draw(ctx,active=true){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.a);ctx.shadowColor=active?'#65f6c0':'transparent';ctx.shadowBlur=active?15:0;ctx.fillStyle=this.color;roundRect(ctx,-17,-31,34,62,8);ctx.fill();ctx.fillStyle='#bce8ff';roundRect(ctx,-12,-18,24,16,4);ctx.fill();ctx.fillStyle='#16304a';roundRect(ctx,-12,5,24,15,4);ctx.fill();ctx.fillStyle='#111';[-20,16].forEach(x=>[-20,20].forEach(y=>ctx.fillRect(x,y,4,13)));ctx.fillStyle='#fff6b2';ctx.fillRect(-12,-30,7,3);ctx.fillRect(5,-30,7,3);ctx.restore()}
  }
  class TrafficCar extends Car{
    constructor(x,y,axis,speed,min,max,color){super(x,y,axis==='x'?(speed>0?Math.PI/2:-Math.PI/2):(speed>0?Math.PI:0),color);Object.assign(this,{axis,trafficSpeed:speed,min,max})}
    updateTraffic(dt,blockers=[]){const old=this[this.axis];this[this.axis]+=this.trafficSpeed*dt;if(this[this.axis]>this.max)this[this.axis]=this.min;if(this[this.axis]<this.min)this[this.axis]=this.max;const safety=this.corners(this.x,this.y,this.a,this.w+8,this.h+36);const blocked=blockers.some(c=>{if(!c)return false;const delta=c[this.axis]-this[this.axis],ahead=this.trafficSpeed>0?delta>=0:delta<=0;return ahead&&sat(safety,c.corners(c.x,c.y,c.a,c.w+8,c.h+36))});if(blocked){this[this.axis]=old;return false}return true}
  }
  class Bus extends Car{
    constructor(x,y,a,color='#f6b73c'){super(x,y,a,color);this.w=46;this.h=104}
    draw(ctx,active=true){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.a);ctx.shadowColor=active?'#65f6c0':'transparent';ctx.shadowBlur=active?16:0;ctx.fillStyle=this.color;roundRect(ctx,-23,-52,46,104,9);ctx.fill();ctx.fillStyle='#bde9ff';roundRect(ctx,-17,-44,34,16,4);ctx.fill();ctx.fillStyle='#24364a';for(let y=-20;y<=27;y+=16){ctx.fillRect(-20,y,7,10);ctx.fillRect(13,y,7,10)}ctx.fillStyle='#fff1a8';ctx.fillRect(-16,-51,10,4);ctx.fillRect(6,-51,10,4);ctx.fillStyle='#18212c';[-27,23].forEach(x=>[-33,24].forEach(y=>ctx.fillRect(x,y,5,18)));ctx.fillStyle='#fff';ctx.font='bold 9px sans-serif';ctx.textAlign='center';ctx.fillText('ÔNIBUS',0,47);ctx.restore()}
  }
  class ParkingSpot{
    constructor(x,y,a,n,w=48,h=82){Object.assign(this,{x,y,a,n,w,h})}
    contains(car){const p=car.corners();const c=Math.cos(-this.a),s=Math.sin(-this.a);return p.every(q=>{const dx=q.x-this.x,dy=q.y-this.y;return Math.abs(dx*c-dy*s)<this.w/2-2&&Math.abs(dx*s+dy*c)<this.h/2-2})}
    draw(ctx,target=false,t=0){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.a);ctx.strokeStyle=target?(Math.sin(t*6)>0?'#56ffaf':'#fff176'):'#d8e3e8';ctx.lineWidth=target?5:2;ctx.setLineDash(target?[10,6]:[]);ctx.strokeRect(-this.w/2,-this.h/2,this.w,this.h);ctx.setLineDash([]);ctx.fillStyle=target?'#56ffaf':'#d8e3e8';ctx.font='bold 17px sans-serif';ctx.textAlign='center';ctx.fillText(target?'ALVO '+this.n:String(this.n),0,6);ctx.restore()}
  }
  const levels=[
    {start:[100,500,0],cars:2,spots:[[770,130,Math.PI/2],[770,470,Math.PI/2]],obs:[[380,245,100,110]]},
    {start:[100,300,Math.PI/2],cars:3,spots:[[780,110,Math.PI/2],[780,300,Math.PI/2],[780,490,Math.PI/2]],obs:[[400,80,70,180],[400,340,70,180]]},
    {start:[120,500,0],cars:3,spots:[[170,105,0],[500,105,0],[830,105,0]],obs:[[300,260,400,70],[70,180,100,55]]},
    {start:[500,520,0],cars:4,spots:[[120,110,Math.PI/2],[880,110,Math.PI/2],[120,330,Math.PI/2],[880,330,Math.PI/2]],obs:[[280,190,440,65],[280,390,440,65]]},
    {start:[100,510,0],cars:5,spots:[[170,100,0],[390,100,0],[610,100,0],[830,100,0],[880,485,Math.PI/2]],obs:[[250,210,80,260],[460,210,80,260],[670,210,80,260],[50,180,100,70]]},
    {name:'Desafio da baliza',hint:'Faça a baliza na vaga piscando, entre os dois carros.',start:[500,500,0],cars:1,spots:[[500,115,Math.PI/2]],staticCars:[[410,115,Math.PI/2,'#e75858'],[590,115,Math.PI/2,'#f2b84b']],obs:[[250,205,500,45]]},
    {name:'Avenida movimentada',hint:'Atravesse a avenida com atenção ao trânsito e estacione no outro lado.',road:true,start:[90,500,0],cars:1,spots:[[885,95,Math.PI/2]],staticCars:[[790,95,Math.PI/2,'#9b7bff']],traffic:[[160,355,'x',92,45,955,'#ef5350'],[820,270,'x',-115,45,955,'#ffd166']],obs:[[25,180,260,35],[715,180,260,35]]},
    {name:'Corredor urbano',hint:'Acompanhe o fluxo, troque de faixa e alcance as duas vagas.',road:true,start:[80,520,0],cars:2,spots:[[875,105,Math.PI/2],[875,495,Math.PI/2]],staticCars:[[785,105,Math.PI/2,'#31c48d'],[785,495,Math.PI/2,'#ff7a59']],traffic:[[120,350,'x',125,45,955,'#ef5350'],[760,265,'x',-105,45,955,'#47a7ff'],[510,350,'x',88,45,955,'#f2b84b']],obs:[[25,180,180,32],[795,385,180,32]]},
    {name:'Baliza dupla',hint:'Estacione dois carros em vagas apertadas sem tocar nos veículos vizinhos.',start:[500,520,0],cars:2,spots:[[350,105,Math.PI/2],[650,105,Math.PI/2]],staticCars:[[265,105,Math.PI/2,'#ef5350'],[435,105,Math.PI/2,'#47a7ff'],[565,105,Math.PI/2,'#f2b84b'],[735,105,Math.PI/2,'#31c48d']],obs:[[250,205,500,40],[410,360,180,70]]},
    {name:'Trânsito avançado',hint:'Desvie dos carros em movimento e conclua uma baliza no fim da avenida.',road:true,start:[80,515,0],cars:2,spots:[[850,105,Math.PI/2],[500,495,Math.PI/2]],staticCars:[[765,105,Math.PI/2,'#ef5350'],[935,105,Math.PI/2,'#31c48d'],[415,495,Math.PI/2,'#9b7bff'],[585,495,Math.PI/2,'#f2b84b']],traffic:[[100,350,'x',135,45,955,'#ff5964'],[900,270,'x',-125,45,955,'#47a7ff'],[470,350,'x',105,45,955,'#ffffff']],obs:[[25,180,240,34],[735,180,240,34]]},
    {name:'Motorista de ônibus',hint:'Faça a baliza com o ônibus na vaga longa entre os dois ônibus parados.',road:true,vehicle:'bus',start:[100,500,0],cars:1,spots:[[775,100,Math.PI/2,70,130]],staticBuses:[[630,100,Math.PI/2,'#e75858'],[920,100,Math.PI/2,'#31c48d']],traffic:[[100,350,'x',105,45,955,'#ef5350'],[850,270,'x',-95,45,955,'#47a7ff']],obs:[[25,180,250,34],[725,180,250,34]]},
    {name:'Baliza no meio da rua',hint:'Estacione junto ao mesmo meio-fio dos carros enquanto a fila aguarda.',road:true,waitAfterPark:true,start:[500,330,Math.PI/2],cars:1,spots:[[650,170,Math.PI/2]],staticCars:[[560,170,Math.PI/2,'#9b7bff'],[740,170,Math.PI/2,'#f2b84b']],traffic:[[380,330,'x',72,45,955,'#ef5350'],[265,330,'x',72,45,955,'#47a7ff'],[150,330,'x',72,45,955,'#31c48d']],obs:[[25,105,410,30],[865,105,110,30]]}
  ];
  class Game{
    constructor(){this.canvas=$('game');this.ctx=this.canvas.getContext('2d');this.input=new InputManager();this.audio=new AudioManager();this.state='menu';this.level=0;this.score=0;this.best=+(localStorage.getItem('ef-best')||0);this.last=performance.now();this.elapsed=0;this.parked=0;this.crashes=0;this.hitCooldown=0;this.parkCooldown=0;this.bind();this.loadLevel();requestAnimationFrame(t=>this.loop(t))}
    bind(){$('mainBtn').onclick=()=>this.mainAction();$('pauseBtn').onclick=()=>this.togglePause();$('restartBtn').onclick=()=>this.restart();$('soundBtn').onclick=()=>this.updateSound(this.audio.toggle());this.updateSound(this.audio.enabled);addEventListener('blur',()=>{if(this.state==='playing')this.pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.state==='playing')this.pause()})}
    loadLevel(){const L=levels[this.level];this.parked=0;this.levelTime=0;this.waitingFinish=false;this.spots=L.spots.map((s,i)=>new ParkingSpot(s[0],s[1],s[2],i+1,s[3],s[4]));this.obstacles=(L.obs||[]).map(o=>({x:o[0],y:o[1],w:o[2],h:o[3]}));this.parkedCars=[];this.staticCars=[...(L.staticCars||[]).map(s=>new Car(...s)),...(L.staticBuses||[]).map(s=>new Bus(...s))];this.trafficCars=(L.traffic||[]).map(s=>new TrafficCar(...s));$('levelHint').textContent=L.hint||'Vaga-alvo piscando • pare e alinhe o carro completamente dentro dela';this.spawn();this.updateHUD()}
    spawn(){const L=levels[this.level],shift=this.parked*7,color=['#2fa8ff','#ff5964','#ffb627','#9b7bff','#32d583'][this.parked%5],Vehicle=L.vehicle==='bus'?Bus:Car;this.car=new Vehicle(L.start[0]+shift,L.start[1],L.start[2],color)}
    mainAction(){this.audio.init();if(this.state==='menu'||this.state==='gameover'){this.level=0;this.score=0;this.crashes=0;this.elapsed=0;this.loadLevel();this.play()}else if(this.state==='complete'){if(this.level<levels.length-1){this.level++;this.loadLevel();this.play()}else{this.showEnd()}}else if(this.state==='paused')this.play()}
    play(){this.state='playing';$('overlay').classList.add('hidden');this.last=performance.now();this.audio.startMusic();$('pauseBtn').textContent='⏸ Pausar'}
    pause(){this.state='paused';this.input.clear();this.audio.stopMusic();this.showOverlay('Jogo pausado','Respire fundo. Seu carro está seguro.','Continuar',false);$('pauseBtn').textContent='▶ Continuar'}
    togglePause(){if(this.state==='playing')this.pause();else if(this.state==='paused')this.play()}
    restart(){if(this.state==='menu')return;this.score=Math.max(0,this.score-100);this.loadLevel();this.play()}
    showOverlay(title,text,button,instructions=false){$('overlayTitle').textContent=title;$('overlayText').textContent=text;$('mainBtn').textContent=button;$('instructions').style.display=instructions?'grid':'none';$('overlay').classList.remove('hidden')}
    updateSound(on){$('soundBtn').textContent=on?'🔊 Som':'🔇 Sem som';$('soundBtn').setAttribute('aria-pressed',String(on));if(on&&this.state==='playing')this.audio.startMusic()}
    loop(now){const dt=Math.min((now-this.last)/1000,.035);this.last=now;if(this.state==='playing')this.update(dt);this.draw(now/1000);requestAnimationFrame(t=>this.loop(t))}
    update(dt){this.elapsed+=dt;this.levelTime+=dt;this.hitCooldown-=dt;this.parkCooldown-=dt;this.trafficCars.forEach(c=>c.updateTraffic(dt,[this.car,...this.staticCars,...this.parkedCars,...this.trafficCars.filter(o=>o!==c)]));if(this.waitingFinish){this.finishCountdown-=dt;this.updateHUD();if(this.finishCountdown<=0)this.completeLevel();return}const old={x:this.car.x,y:this.car.y,a:this.car.a};this.car.update(dt,this.input);if(this.collides(this.car)){Object.assign(this.car,old);this.car.speed*=-.25;if(this.hitCooldown<=0){this.crashes++;this.score=Math.max(0,this.score-40);this.hitCooldown=.8;this.audio.crash();this.canvas.classList.add('impact');setTimeout(()=>this.canvas.classList.remove('impact'),400);this.toast('💥 Batida! −40 pontos')}}
      const spot=this.spots[this.parked];if(this.parkCooldown<=0&&spot.contains(this.car)&&Math.abs(this.car.speed)<10&&angleDiff(this.car.a,spot.a)<.28){this.parkCooldown=1;const ParkedVehicle=this.car instanceof Bus?Bus:Car;this.parkedCars.push(new ParkedVehicle(spot.x,spot.y,spot.a,this.car.color));this.parked++;const precision=Math.round(300+Math.max(0,180-this.levelTime*3));this.score+=precision;this.audio.park();this.toast('✅ Perfeito! +'+precision);this.levelTime=0;if(this.parked>=levels[this.level].cars){if(levels[this.level].waitAfterPark){this.waitingFinish=true;this.finishCountdown=3.5;this.car=null;$('levelHint').textContent='Manobra concluída! Observe os carros retomando o caminho.'}else this.completeLevel()}else this.spawn()}this.updateHUD()}
    collides(car){const pts=car.corners();if(pts.some(p=>p.x<25||p.x>W-25||p.y<25||p.y>H-25))return true;return this.obstacles.some(o=>polyRect(pts,o))||[...this.parkedCars,...this.staticCars,...this.trafficCars].some(c=>sat(pts,c.corners()))}
    completeLevel(){this.state='complete';this.audio.stopMusic();const bonus=Math.max(100,Math.round(800-this.levelTime*5-this.crashes*20));this.score+=bonus;this.saveBest();this.audio.complete();const last=this.level===levels.length-1;this.showOverlay(last?'Você dominou o estacionamento!':'Fase concluída!',`Pontuação: ${this.score} • Batidas: ${this.crashes} • Bônus: ${bonus}`,last?'Ver resultado':'Próxima fase')}
    showEnd(){this.state='gameover';this.audio.stopMusic();this.saveBest();this.showOverlay('Fim de jogo — parabéns!',`Você concluiu as ${levels.length} fases com ${this.score} pontos e ${this.crashes} batidas. Recorde: ${this.best}.`,'Jogar novamente')}
    saveBest(){if(this.score>this.best){this.best=this.score;localStorage.setItem('ef-best',this.best)}localStorage.setItem('ef-level',Math.max(+(localStorage.getItem('ef-level')||1),this.level+1))}
    toast(s){const e=$('message');e.textContent=s;e.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>e.classList.remove('show'),1200)}
    updateHUD(){$('phase').textContent=this.level+1;$('score').textContent=this.score;$('time').textContent=formatTime(this.elapsed);$('parked').textContent=this.parked;$('remaining').textContent=levels[this.level].cars-this.parked;$('crashes').textContent=this.crashes;$('best').textContent=this.best}
    draw(t){const c=this.ctx,L=levels[this.level];c.clearRect(0,0,W,H);c.fillStyle='#29353b';c.fillRect(0,0,W,H);c.strokeStyle='#33434b';c.lineWidth=2;for(let x=-H;x<W;x+=80){c.beginPath();c.moveTo(x,0);c.lineTo(x+H,H);c.stroke()}if(L.road){c.fillStyle='#20292f';c.fillRect(25,220,950,190);c.strokeStyle='#f5f1d0';c.lineWidth=4;c.setLineDash([30,22]);c.beginPath();c.moveTo(30,315);c.lineTo(970,315);c.stroke();c.setLineDash([])}c.fillStyle='#66737a';c.fillRect(0,0,W,25);c.fillRect(0,H-25,W,25);c.fillRect(0,0,25,H);c.fillRect(W-25,0,25,H);if(!L.road){c.fillStyle='#f4d35e';for(let x=45;x<W-40;x+=70)c.fillRect(x,H/2-3,36,6)}
      this.spots.forEach((s,i)=>s.draw(c,i===this.parked,t));this.obstacles.forEach(o=>{c.fillStyle='#d9574e';roundRect(c,o.x,o.y,o.w,o.h,8);c.fill();c.strokeStyle='#fff';c.lineWidth=5;for(let x=o.x+10;x<o.x+o.w;x+=25){c.beginPath();c.moveTo(x,o.y);c.lineTo(Math.min(x+30,o.x+o.w),o.y+o.h);c.stroke()}});this.staticCars.forEach(x=>x.draw(c,false));this.parkedCars.forEach(x=>x.draw(c,false));this.trafficCars.forEach(x=>x.draw(c,false));if(this.car)this.car.draw(c,true);if(this.state==='paused'){c.fillStyle='#0006';c.fillRect(0,0,W,H)}}
  }
  function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect?c.roundRect(x,y,w,h,r):(c.rect(x,y,w,h))}
  function formatTime(s){const m=Math.floor(s/60),q=Math.floor(s%60);return String(m).padStart(2,'0')+':'+String(q).padStart(2,'0')}
  function angleDiff(a,b){let d=Math.abs((a-b)%(Math.PI*2));return Math.min(d,Math.PI*2-d,Math.abs(d-Math.PI))}
  function polyRect(p,o){return sat(p,[{x:o.x,y:o.y},{x:o.x+o.w,y:o.y},{x:o.x+o.w,y:o.y+o.h},{x:o.x,y:o.y+o.h}])}
  function sat(a,b){for(const p of [a,b])for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length],e={x:q.x-p[i].x,y:q.y-p[i].y},axis={x:-e.y,y:e.x};let amin=Infinity,amax=-Infinity,bmin=Infinity,bmax=-Infinity;for(const v of a){const d=v.x*axis.x+v.y*axis.y;amin=Math.min(amin,d);amax=Math.max(amax,d)}for(const v of b){const d=v.x*axis.x+v.y*axis.y;bmin=Math.min(bmin,d);bmax=Math.max(bmax,d)}if(amax<bmin||bmax<amin)return false}return true}
  const game=new Game();
})();
